name: Deploy Node.js application with Ansible

on:
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 
      image: alpine/ansible:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/ansible_key.pem
          chmod 600 ~/.ssh/ansible_key.pem

      - name: Run Ansible Playbook
        working-directory: ansible
        run: ansible-playbook node_service.yml --tags app



          
